apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promo-serving-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"   # use GKE's built-in controller
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: promo-serving
                port:
                  number: 80