apiVersion: v1
kind: Service
metadata:
  name: promo-serving
spec:
  type: ClusterIP        # changed from LoadBalancer — internal only now
  selector:
    app: promo-serving
  ports:
    - port: 80
      targetPort: 8080